CREATE TABLE IF NOT EXISTS player_last_location (
    identifier VARCHAR(50) PRIMARY KEY,
    last_x FLOAT NOT NULL,
    last_y FLOAT NOT NULL,
    last_z FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
